Clarify Perfetto release branch requirment
olvaffe/percetto pull request #16
Opened 2021-05-04 14:04 UTC by Wallbraker

Make it super clear that you have to checkout a release branch

2022-02-15 15:09 UTC, batesj approved these changes

2022-02-15 15:11 UTC, batesj requested changes

2022-02-15 15:11 UTC, batesj commented on README.md
> +Perfetto, make sure to checkout a relesae branch as the `main` branch does
Please fix typo:

relesae -> release

2022-02-16 18:44 UTC, Wallbraker commented
@batesj Done

2022-02-16 21:51 UTC, merged